### ISSUE TITLE
actions not worked

### ISSUE THREAD

**Issue by Ningensei848** [Ningensei848/Ningensei848#2]
PERSONAL_ACCESS_TOKEN を設定しておらず，アクションの実行がコケた．

```
steps:
  - uses: actions/checkout@v2
  - uses: vn7n24fzkq/github-profile-summary-cards@release
    env: # default use ${{ secrets.GITHUB_TOKEN }}, you can change to your personal access token
      GITHUB_TOKEN: ${{ secrets.README }}
    with:
      USERNAME: ${{ github.repository_owner }}
```

GITHUB_TOKEN が元レポジトリだと `secrets.README` になっていた．これを以下のように変更した．

```
steps:
  - uses: actions/checkout@v2
  - uses: vn7n24fzkq/github-profile-summary-cards@release
    env: # default use ${{ secrets.GITHUB_TOKEN }}, you can change to your personal access token
      GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    with:
      USERNAME: ${{ github.repository_owner }}
```
